/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AccordionElement {
        "opened": boolean;
        "showbtn": boolean;
    }
    interface AccordionItem {
        "acctitle": string;
        "show": boolean;
    }
}
export interface AccordionItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAccordionItemElement;
}
declare global {
    interface HTMLAccordionElementElement extends Components.AccordionElement, HTMLStencilElement {
    }
    var HTMLAccordionElementElement: {
        prototype: HTMLAccordionElementElement;
        new (): HTMLAccordionElementElement;
    };
    interface HTMLAccordionItemElement extends Components.AccordionItem, HTMLStencilElement {
    }
    var HTMLAccordionItemElement: {
        prototype: HTMLAccordionItemElement;
        new (): HTMLAccordionItemElement;
    };
    interface HTMLElementTagNameMap {
        "accordion-element": HTMLAccordionElementElement;
        "accordion-item": HTMLAccordionItemElement;
    }
}
declare namespace LocalJSX {
    interface AccordionElement {
        "opened"?: boolean;
        "showbtn"?: boolean;
    }
    interface AccordionItem {
        "acctitle"?: string;
        "onItemClicked"?: (event: AccordionItemCustomEvent<any>) => void;
        "show"?: boolean;
    }
    interface IntrinsicElements {
        "accordion-element": AccordionElement;
        "accordion-item": AccordionItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "accordion-element": LocalJSX.AccordionElement & JSXBase.HTMLAttributes<HTMLAccordionElementElement>;
            "accordion-item": LocalJSX.AccordionItem & JSXBase.HTMLAttributes<HTMLAccordionItemElement>;
        }
    }
}
